from fibonacci import fibonacci
from binario import binario
from Hexadecimal import hexadecimal
from padovan import padovan 
from Feliz import NumeroFeliz
from capicua import capicua

class pruebas:

 fibo = fibonacci()
 bina = binario()
 hexa = hexadecimal()


 print("****Fibonacci*****")
 print(fibo.avanzar())
 print(fibo.avanzar())
 print(fibo.avanzar())
 print(fibo.avanzar())
 print(fibo.avanzar())
 print(fibo.avanzar())
 print(fibo.avanzar())
 print(fibo.avanzar())
 print(fibo.avanzar())
 print(fibo.anterior())
 print(fibo.anterior())
 print(fibo.anterior())
 print(fibo.anterior())
 print("****Binario*****")
 
 numero = fibo.avanzar()
 numero1 = fibo.avanzar()
 numero2 = fibo.avanzar()
 numero3 = fibo.avanzar()
 numero4 = fibo.avanzar()
 numero5 = fibo.avanzar()
 numero6 = fibo.avanzar()
 print(bina.binarizar(numero))
 print(bina.binarizar(numero1))
 print(bina.binarizar(numero2))
 print(bina.binarizar(numero3))
 print(bina.binarizar(numero4))
 print(bina.binarizar(numero5))
 print(bina.binarizar(numero6))
 print("****Hexadecimal*****")

 numero = fibo.avanzar()
 print(hexa.DecimalAHexadecimal(numero))
 numero1 = fibo.avanzar()
 print(hexa.DecimalAHexadecimal(numero1))
 numero2 = fibo.avanzar()
 print(hexa.DecimalAHexadecimal(numero2))
 numero3 = fibo.avanzar()
 print(hexa.DecimalAHexadecimal(numero3))
 numero4 = fibo.avanzar()
 print(hexa.DecimalAHexadecimal(numero4))
 numero5 = fibo.avanzar()
 print(hexa.DecimalAHexadecimal(numero5))
 numero6 = fibo.avanzar()
 print(hexa.DecimalAHexadecimal(numero6))
 numero7 = fibo.avanzar()
 print(hexa.DecimalAHexadecimal(numero7))

 print("*****Numero feliz***")
 feliz = NumeroFeliz()
 print(feliz.esfeliz(str(numero))) 
 print("***Numero capicua****")
 cap = capicua()
 cap.capicua(numero)
 print(cap.resultadoCapicua())
 print("***Numero padovan***")
 padov = padovan()
 print(padov.avanzar())
 print(padov.avanzar())
 print(padov.avanzar())
 print(padov.avanzar())
 print(padov.avanzar())
 print(padov.avanzar())
 print(padov.avanzar())
 print(padov.avanzar())
 print(padov.avanzar())
 print(padov.avanzar())
 print(padov.avanzar())
 print(padov.avanzar())
 print(padov.avanzar())
 print(padov.avanzar())
 print("anterior")
 print(padov.anterior())
 print(padov.siguiente())
#print(padov.anterior())
